name: scope_generator
description: Analysis server plugin to generate Flutter Scope boilerplate from Listenable-based controllers
version: 1.0.0

environment:
  sdk: ^3.10.0

dependencies:
  analysis_server_plugin: ^0.3.4
  analyzer: ^9.0.0
  analyzer_plugin: ^0.13.11

dev_dependencies:
  lints: ^6.0.0
  test: ^1.29.0
