name: example
description: Example for scope_generator plugin
version: 1.0.0

environment:
  sdk: ^3.10.4
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  control: 0.2.0
  

dev_dependencies:
  lints: ^6.0.0
